name: Test

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'

jobs:
  VTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        haproxy-versions:
        - "1.8"
        - "1.9"
        - "2.0"
        - "2.1"
        - "2.2"
        - "2.3"
      fail-fast: false
    steps:
    - name: Install HAProxy ${{ matrix.haproxy-versions }}.
      uses: chipitsine/action-install-haproxy@main
      id: install-haproxy
      with:
        branch: ${{ matrix.haproxy-versions }}
        install_vtest: yes
        use_lua: yes
    - name: Install apt dependencies.
      run: sudo apt-get install -y lua-json
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install haproxy-lua-http globally.
      run: |
        sudo install -m755 -d /usr/local/share/lua/5.3/
        sudo install -m644 haproxy-lua-http/http.lua /usr/local/share/lua/5.3/haproxy-lua-http.lua
        sed -i 's/lua-prepend-path/#lua-prepend-path/g' test/*.vtc
    - name: Run tests using HAProxy ${{ steps.install-haproxy.outputs.version }}.
      run: vtest -Dhaproxy_version=${{ steps.install-haproxy.outputs.version }} -k -t 10 test/*.vtc
